AWSTemplateFormatVersion: '2010-09-09'
Description: 'Setup GitHub OIDC provider and IAM roles for GitHub Actions deployments in Development Account (615299752206)'

Parameters:
  GitHubOrg:
    Type: String
    Default: Third-Opinion
    Description: GitHub organization name
  
  GitHubRepo:
    Type: String
    Default: AppInfraCdkV1
    Description: GitHub repository name

Resources:
  # GitHub OIDC Provider
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Tags:
        - Key: Purpose
          Value: GitHubActionsOIDC
        - Key: Environment
          Value: Development

  # Development Deployment Role
  GitHubActionsDevDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-dev-deploy
      Description: Role for GitHub Actions to deploy to development environment
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': sts.amazonaws.com
              StringLike:
                'token.actions.githubusercontent.com:sub':
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/develop'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/development'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/feature/*'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/master'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:pull_request'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/*'
                  - !Sub 'repo:${GitHubOrg}/TrialFinder:ref:refs/heads/develop'
                  - !Sub 'repo:${GitHubOrg}/TrialFinder:ref:refs/heads/development'
                  - !Sub 'repo:${GitHubOrg}/TrialFinder:ref:refs/heads/feature/*'
                  - !Sub 'repo:${GitHubOrg}/TrialFinder:ref:refs/heads/master'
                  - !Sub 'repo:${GitHubOrg}/TrialFinder:ref:refs/heads/main'
                  - !Sub 'repo:${GitHubOrg}/TrialFinder:pull_request'
                  - !Sub 'repo:${GitHubOrg}/TrialFinder:ref:refs/heads/*'
      ManagedPolicyArns:
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/dev-g-policy-g-gh-cdk-deploy'
      Tags:
        - Key: Purpose
          Value: GitHubActionsDeployment
        - Key: Environment
          Value: Development
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  GitHubOIDCProviderArn:
    Description: ARN of the GitHub OIDC Provider
    Value: !Ref GitHubOIDCProvider
    Export:
      Name: !Sub '${AWS::StackName}-GitHubOIDCProviderArn'
  
  DevDeployRoleArn:
    Description: ARN of the GitHub Actions deployment role for development
    Value: !GetAtt GitHubActionsDevDeployRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DevDeployRoleArn'