AWSTemplateFormatVersion: '2010-09-09'
Description: 'Setup GitHub OIDC provider and IAM roles for GitHub Actions deployments in Production Account (442042533707)'

Parameters:
  GitHubOrg:
    Type: String
    Default: Third-Opinion
    Description: GitHub organization name
  
  GitHubRepo:
    Type: String
    Default: AppInfraCdkV1
    Description: GitHub repository name

Resources:
  # GitHub OIDC Provider
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Tags:
        - Key: Purpose
          Value: GitHubActionsOIDC
        - Key: Environment
          Value: Production

  # Production Deployment Role
  GitHubActionsProdDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-prod-deploy
      Description: Role for GitHub Actions to deploy to production environment
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': sts.amazonaws.com
              StringLike:
                'token.actions.githubusercontent.com:sub':
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/master'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main'
      Policies:
        - PolicyName: CDKDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CDKBootstrapAndMetadata
                Effect: Allow
                Action:
                  - cloudformation:*
                  - ssm:GetParameter
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                  - ssm:DescribeParameters
                Resource:
                  - !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/CDKToolkit/*'
                  - !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/prod-*'
                  - !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/stg-*'
                  - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/cdk-bootstrap/*'
                  - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/*'
              
              - Sid: S3ForCDKAssets
                Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - 'arn:aws:s3:::cdk-*'
                  - 'arn:aws:s3:::thirdopinion.io-*'
                  - 'arn:aws:s3:::prod-*'
                  - 'arn:aws:s3:::stg-*'
              
              - Sid: ECRServices
                Effect: Allow
                Action:
                  - ecr:*
                Resource: '*'
              
              - Sid: CoreServices
                Effect: Allow
                Action:
                  - ec2:*
                  - autoscaling:*
                  - elasticloadbalancing:*
                  - ecs:*
                  - lambda:*
                  - states:*
                  - rds:*
                  - dynamodb:*
                  - elasticache:*
                  - apigateway:*
                  - cloudfront:*
                  - route53:*
                  - sqs:*
                  - sns:*
                  - events:*
                  - logs:*
                  - cloudwatch:*
                  - xray:*
                  - cognito-idp:*
                  - cognito-identity:*
                  - ses:*
                  - amplify:*
                  - bedrock:*
                  - sagemaker:*
                Resource: '*'
              
              - Sid: SecretsManagerTaggedAccess
                Effect: Allow
                Action:
                  - secretsmanager:*
                Resource: '*'
                Condition:
                  StringEquals:
                    'secretsmanager:ResourceTag/CDKManaged': 'true'
              
              - Sid: SecretsManagerCreateTagged
                Effect: Allow
                Action:
                  - secretsmanager:CreateSecret
                  - secretsmanager:TagResource
                Resource: '*'
                Condition:
                  StringEquals:
                    'aws:RequestTag/CDKManaged': 'true'
              
              - Sid: IAMRoleManagement
                Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:UpdateRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:PassRole
                  - iam:CreateServiceLinkedRole
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/cdk-*'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/prod-*'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/stg-*'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/*'
              
              - Sid: ReadOnlyAccess
                Effect: Allow
                Action:
                  - kms:DescribeKey
                  - kms:ListAliases
                  - acm:ListCertificates
                  - acm:DescribeCertificate
                  - sts:AssumeRole
                  - tag:TagResources
                  - tag:UntagResources
                  - tag:GetResources
                Resource: '*'
      Tags:
        - Key: Purpose
          Value: GitHubActionsDeployment
        - Key: Environment
          Value: Production
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  GitHubOIDCProviderArn:
    Description: ARN of the GitHub OIDC Provider
    Value: !Ref GitHubOIDCProvider
    Export:
      Name: !Sub '${AWS::StackName}-GitHubOIDCProviderArn'
  
  ProdDeployRoleArn:
    Description: ARN of the GitHub Actions deployment role for production
    Value: !GetAtt GitHubActionsProdDeployRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ProdDeployRoleArn'