name: Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      app:
        description: 'Application to deploy'
        required: true
        default: 'TrialFinderV2'
        type: choice
        options:
        - TrialFinderV2
        # Add other registered applications here
      confirm:
        description: 'Type "deploy" to confirm production deployment'
        required: true
        default: ''

env:
  CDK_ENVIRONMENT: Production
  AWS_REGION: us-east-2

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  validate-input:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm }}" != "deploy" ]; then
          echo "❌ Deployment cancelled - confirmation not provided"
          exit 1
        fi
        echo "✅ Production deployment confirmed"

  validate-naming:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ github.event_name == 'workflow_dispatch' && fromJson(format('["{0}"]', github.event.inputs.app)) || fromJson('["TrialFinderV2"]') }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore AppInfraCdkV1.sln
    
    - name: Build
      run: dotnet build AppInfraCdkV1.sln --no-restore --configuration Release
    
    - name: Validate Naming
      run: |
        cd AppInfraCdkV1.Deploy
        echo "🔍 Validating naming for ${{ matrix.app }} in ${{ env.CDK_ENVIRONMENT }}..."
        dotnet run -- --app=${{ matrix.app }} --environment=${{ env.CDK_ENVIRONMENT }} --validate-only
        echo "✅ Naming validated for production deployment"
    
    - name: Display Production Resource Names
      run: |
        cd AppInfraCdkV1.Deploy
        echo "📝 Production resource names that will be created:"
        dotnet run -- --app=${{ matrix.app }} --environment=${{ env.CDK_ENVIRONMENT }} --show-names-only

  deploy-base-prod:
    needs: [validate-input, validate-naming]
    if: always() && (needs.validate-input.result == 'success' || github.event_name == 'push') && needs.validate-naming.result == 'success'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup Node.js (for CDK CLI)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install CDK CLI
      run: npm install -g aws-cdk
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/prod-tfv2-role-ue2-github-actions
        role-session-name: GitHubActions-Deploy-${{ github.run_id }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Restore dependencies
      run: dotnet restore AppInfraCdkV1.sln
    
    - name: Build
      run: dotnet build AppInfraCdkV1.sln --no-restore --configuration Release
    
    - name: Run tests
      run: dotnet test AppInfraCdkV1.sln --no-build --configuration Release --verbosity normal
    
    - name: CDK Diff for Base Stack
      run: |
        cd AppInfraCdkV1.Deploy
        echo "🔍 Checking production base stack changes..."
        cdk diff --app="dotnet run -- --deploy-base --environment=${{ env.CDK_ENVIRONMENT }}"
    
    - name: Deploy Base Stack to Production
      run: |
        cd AppInfraCdkV1.Deploy
        echo "🚀 Deploying base infrastructure to PRODUCTION environment..."
        echo "⚠️  This is a PRODUCTION deployment!"
        cdk deploy --app="dotnet run -- --deploy-base --environment=${{ env.CDK_ENVIRONMENT }}" \
                  --require-approval never \
                  --outputs-file base-outputs.json
        echo "✅ Base stack deployment completed successfully!"
    
    - name: Upload base deployment outputs
      uses: actions/upload-artifact@v4
      with:
        name: base-outputs-prod
        path: AppInfraCdkV1.Deploy/base-outputs.json

  deploy-app-stacks-prod:
    needs: [validate-input, validate-naming, deploy-base-prod]
    if: always() && (needs.validate-input.result == 'success' || github.event_name == 'push') && needs.validate-naming.result == 'success' && needs.deploy-base-prod.result == 'success'
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        app: ${{ github.event_name == 'workflow_dispatch' && fromJson(format('["{0}"]', github.event.inputs.app)) || fromJson('["TrialFinderV2"]') }}
        stack: [DATA, ALB, ECS]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup Node.js (for CDK CLI)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install CDK CLI
      run: npm install -g aws-cdk
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/prod-tfv2-role-ue2-github-actions
        role-session-name: GitHubActions-Deploy-${{ github.run_id }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Restore dependencies
      run: dotnet restore AppInfraCdkV1.sln
    
    - name: Build
      run: dotnet build AppInfraCdkV1.sln --no-restore --configuration Release
    
    - name: Run tests
      run: dotnet test AppInfraCdkV1.sln --no-build --configuration Release --verbosity normal
    
    - name: CDK Diff for ${{ matrix.stack }} Stack
      run: |
        cd AppInfraCdkV1.Deploy
        echo "🔍 Checking production changes for ${{ matrix.app }} ${{ matrix.stack }} stack..."
        export CDK_STACK_TYPE=${{ matrix.stack }}
        cdk diff --app="dotnet run -- --app=${{ matrix.app }} --environment=${{ env.CDK_ENVIRONMENT }}"
    
    - name: CDK Deploy ${{ matrix.stack }} Stack to Production
      run: |
        cd AppInfraCdkV1.Deploy
        echo "🚀 Deploying ${{ matrix.app }} ${{ matrix.stack }} stack to PRODUCTION environment..."
        echo "⚠️  This is a PRODUCTION deployment!"
        export CDK_STACK_TYPE=${{ matrix.stack }}
        cdk deploy --app="dotnet run -- --app=${{ matrix.app }} --environment=${{ env.CDK_ENVIRONMENT }}" \
                  --require-approval never \
                  --outputs-file ${{ matrix.app }}-${{ matrix.stack }}-outputs.json
        echo "✅ ${{ matrix.stack }} stack deployment completed successfully!"
    
    - name: Display Production Resources
      run: |
        cd AppInfraCdkV1.Deploy
        if [ -f ${{ matrix.app }}-${{ matrix.stack }}-outputs.json ]; then
          echo "📋 Production resources created/updated for ${{ matrix.stack }} stack:"
          cat ${{ matrix.app }}-${{ matrix.stack }}-outputs.json | jq -r 'to_entries[] | "🏭 \(.key): \(.value)"' || cat ${{ matrix.app }}-${{ matrix.stack }}-outputs.json
        fi
    
    - name: Upload deployment outputs
      uses: actions/upload-artifact@v4
      with:
        name: deployment-outputs-${{ matrix.app }}-${{ matrix.stack }}-prod
        path: AppInfraCdkV1.Deploy/${{ matrix.app }}-${{ matrix.stack }}-outputs.json